repos:
  - repo: http://gitlab.eng.cspi.com:8888/3rdParty-Repositories/black.git
    rev: 22.3.0
    hooks:
      - id: black
  - repo: http://gitlab.eng.cspi.com:8888/3rdParty-Repositories/flake8.git
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: http://gitlab.eng.cspi.com:8888/3rdParty-Repositories/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
